service: auction-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iam:
    role:
      statements: ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: handler.createAuction
    events:
      - http:
          method: POST
          path: auction

  getAuctions:
    handler: handler.getAuctions
    events:
      - http:
          method: GET
          path: auctions

  getAuction:
    handler: handler.getAuction
    events:
      - http:
          method: GET
          path: auction/{id}
          request:
            parameters:
              paths:
                id: true

  placeBid:
    handler: handler.placeBid
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          request:
            parameters:
              paths:
                id: true

  processAuctions:
    handler: handler.processAuctions
    events:
      - schedule: rate(1 minute)

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
